/**************************************************************
CAUTION : This file is Auto Generated by VBA based on *.xls.
          So, don't modify this file manually!
***************************************************************/
#ifndef CPE_IOS_AO_CONFIG_H_
#define CPE_IOS_AO_CONFIG_H_

/*配置管脚复用关系、内部上下拉以及驱动能力*/
#define CPE_IOS_AO_CONFIG \
do{\
\
/*配置PMU(10个PIN)*/\
    /*pmu_hold管脚上下拉配置*/\
    PUSET_IOS_AO_IOM_CTRL8;\
\
\
/*配置USIM0（3个PIN）*/\
\
/*配置UART0（2个PIN）*/\
\
/*配置GPIO(4个PIN）*/\
    /*gpio0[2]管脚上下拉配置*/\
    PUSET_IOS_AO_IOM_CTRL14;\
\
    /*gpio0[3]管脚上下拉配置*/\
    PUSET_IOS_AO_IOM_CTRL15;\
\
    /*pcie_wake_n管脚复用配置*/\
    SET_IOS_PCIE_WAKE_CTRL1_1;\
    CLR_IOS_GPIO0_4_CTRL1_1;\
    /*pcie_wake_n管脚上下拉配置*/\
    PUSET_IOS_AO_IOM_CTRL16;\
\
    /*gpio0[5]管脚上下拉配置*/\
    PUSET_IOS_AO_IOM_CTRL17;\
\
\
/*配置JTAG_DFM_MODE(1个PIN）*/\
\
/*配置USB(5个PIN）*/\
\
}while(0)

/*管脚配置宏for drv*/
#define CPE_IOS_CONFIG \
do{\
    CPE_IOS_AO_CONFIG;\
    CPE_IOS_PD_CONFIG;\
}while(0)

#endif

