/**************************************************************
CAUTION : This file is Auto Generated by VBA based on *.xls.
          So, don't modify this file manually!
***************************************************************/
#ifndef V711_wingle_IOS_AO_CONFIG_H_
#define V711_wingle_IOS_AO_CONFIG_H_

/*配置管脚复用关系、内部上下拉以及驱动能力*/
#define V711_wingle_IOS_AO_CONFIG \
do{\
\
/*配置PMU(10个PIN)*/\
\
/*配置USIM0（3个PIN）*/\
\
/*配置UART0（2个PIN）*/\
\
/*配置GPIO(4个PIN）*/\
    /*gpio0[3]管脚输入方向配置*/\
    gpio_direction_input(GPIO_0_3);\
\
    /*gpio0[4]管脚输入方向配置*/\
    gpio_direction_input(GPIO_0_4);\
\
\
/*配置JTAG_DFM_MODE(1个PIN）*/\
\
/*配置USB(5个PIN）*/\
\
}while(0)

/*管脚配置宏for drv*/
#define V711_wingle_IOS_CONFIG \
do{\
    V711_wingle_IOS_AO_CONFIG;\
    V711_wingle_IOS_PD_CONFIG;\
}while(0)

#endif

