#
# Makefile for the drivers.
#
# Each configuration option enables a list of files.
obj-y	+= dload_nark_core.o
obj-y	+= dload_nark_api.o
obj-y	+= dload_product.o
obj-y	+= dload_mtd_adapter.o

#obj-$(CONFIG_MBB_DLOAD)	+= dload_nark_core.o
#obj-$(CONFIG_MBB_DLOAD)	+= dload_nark_api.o
#obj-$(CONFIG_MBB_DLOAD)	+= dload_product.o
#obj-$(CONFIG_MBB_DLOAD)	+= dload_mtd_adapter.o
