/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
/* This file should be auto-generated by tool, please don't manully modify it.*/

#include "../hisi_battery_data.h"

static struct single_row_lut feimaotui_1500_fcc_temp = {
    .x        = {-20, -10, 0, 25, 40, 60},
    .y        = {1584, 1586, 1540, 1576, 1557, 1559},
    .cols    = 6
};

static struct single_row_lut feimaotui_1500_fcc_sf = {
    .x        = {0, 100, 200, 300, 400, 500},
    .y        = {100, 96, 94, 92, 90, 88},
    .cols    = 6
};

static struct sf_lut feimaotui_1500_pc_sf = {
    .rows        = 1,
    .cols        = 1,
    .row_entries        = {0},
    .percent    = {100},
    .sf            = {
                {100}
    }
};

static struct sf_lut feimaotui_1500_rbatt_sf = {
        .rows           = 28,
        .cols           = 6,
        /* row_entries are temperature */
        .row_entries            = {-20, -10, 0, 25, 40, 60},
        .percent        = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1},
        .sf                     = {
                    {1307,726,329,100,78,87},
                    {1330,753,341,102,78,87},
                    {1355,778,353,103,79,88},
                    {1394,783,368,106,81,90},
                    {1430,789,387,111,84,93},
                    {1490,790,397,118,88,97},
                    {1563,791,398,128,93,103},
                    {1660,801,390,136,101,109},
                    {1768,829,387,130,105,109},
                    {1868,874,400,111,86,94},
                    {1955,928,427,103,80,88},
                    {2030,993,470,104,80,89},
                    {2097,1070,519,107,82,90},
                    {2178,1153,576,111,84,93},
                    {2300,1250,650,112,85,94},
                    {2522,1376,752,111,81,91},
                    {3105,1581,886,113,82,92},
                    {2603,1993,1043,120,83,94},
                    {3562,3142,1081,119,86,94},
                    {4634,4318,1117,120,86,94},
                    {6406,6496,1249,123,87,95},
                    {8636,10573,1393,129,88,96},
                    {11814,15216,1580,138,90,102},
                    {16831,20780,1823,143,92,105},
                    {21847,26342,2274,153,93,108},
                    {26864,31905,3566,175,97,120},
                    {31881,37468,7652,227,105,144},
                    {36898,43032,14128,372,129,224}
                    }
};

static struct pc_temp_ocv_lut feimaotui_1500_pc_temp_ocv = {
    .rows        = 29,
    .cols        = 6,
    .temp        = {-20, -10, 0, 25, 40, 60},
    .percent    = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
    .ocv        = {
                {4180,4178,4175,4185,4167,4174},
                {4067,4078,4087,4104,4093,4096},
                {4006,4023,4037,4056,4047,4049},
                {3958,3976,3996,4016,4008,4009},
                {3913,3935,3961,3980,3974,3975},
                {3874,3897,3926,3948,3943,3943},
                {3840,3863,3892,3919,3915,3915},
                {3815,3835,3859,3890,3889,3888},
                {3795,3813,3830,3860,3861,3860},
                {3778,3798,3809,3829,3828,3828},
                {3762,3784,3794,3807,3806,3806},
                {3747,3773,3784,3793,3792,3791},
                {3732,3763,3774,3783,3782,3780},
                {3716,3751,3766,3775,3774,3772},
                {3700,3737,3755,3765,3764,3762},
                {3681,3720,3743,3749,3743,3741},
                {3659,3695,3724,3729,3723,3721},
                {3648,3655,3694,3700,3696,3695},
                {3585,3587,3649,3668,3665,3662},
                {3556,3558,3640,3663,3661,3657},
                {3534,3532,3632,3657,3655,3651},
                {3512,3501,3622,3649,3648,3644},
                {3474,3461,3608,3639,3637,3632},
                {3428,3417,3584,3618,3614,3610},
                {3383,3374,3545,3578,3574,3571},
                {3337,3331,3486,3523,3520,3515},
                {3291,3287,3402,3451,3449,3441},
                {3246,3244,3302,3355,3352,3341},
                {3200,3200,3200,3200,3200,3200}
            }
};

static struct hisi_smartstar_coul_battery_data feimaotui_1500_battery_data = {
        .id_voltage_min = 2400,
        .id_voltage_max = 2500,
        .fcc            = 1576,
        .fcc_temp_lut        = &feimaotui_1500_fcc_temp,
        .fcc_sf_lut        = &feimaotui_1500_fcc_sf,
        .pc_temp_ocv_lut    = &feimaotui_1500_pc_temp_ocv,
        .pc_sf_lut        = &feimaotui_1500_pc_sf,
        .rbatt_sf_lut        = &feimaotui_1500_rbatt_sf,
        .default_rbatt_mohm        = 222,
        .max_currentmA = 1000,
        .max_voltagemV = 4171,
        .max_cin_currentmA = 1200,
};

