/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
/* This file should be auto-generated by tool, please don't manully modify it.*/

#include "../hisi_battery_data.h"

static struct single_row_lut feimaotui_1780_fcc_temp = {
    .x        = {-20, -10, 0, 25, 40, 60},
    .y        = {1795, 1791, 1791, 1799, 1797, 1788},
    .cols    = 6
};

static struct single_row_lut feimaotui_1780_fcc_sf = {
    .x        = {0, 100, 200, 300, 400, 500},
    .y        = {100, 96, 94, 92, 90, 88},
    .cols    = 6
};

static struct sf_lut feimaotui_1780_pc_sf = {
    .rows        = 1,
    .cols        = 1,
    .row_entries        = {0},
    .percent    = {100},
    .sf            = {
                {100}
    }
};

static struct sf_lut feimaotui_1780_rbatt_sf = {
        .rows           = 28,
        .cols           = 6,
        /* row_entries are temperature */
        .row_entries            = {-20, -10, 0, 25, 40, 60},
        .percent        = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1},
        .sf                     = {
                    {1542,    793, 402,    100,    71,    62},
                    {1491,    798, 411,    102,    72,    64},
                    {1439,    802, 420,    104,    72,    65},
                    {1347,    777, 421,    106,    74,    65},
                    {1319,    755, 430,    111,    76,    67},
                    {1296,    747, 446,    118,    78,    68},
                    {1293,    729, 446,    129,    83,    70},
                    {1289,    727, 412,    145,    93,    76},
                    {1315,    728, 392,    149,    109,86},
                    {1357,    742, 384,    108,    78,    68},
                    {1410,    783, 384,    103,    73,    66},
                    {1476,    830, 396,    105,    75,    67},
                    {1554,    896, 419,    107,    77,    68},
                    {1651,    967, 455,    107,    79,    70},
                    {1766,    1054, 505,    109,    79,    70},
                    {1893,    1168, 558,    109,    74,    66},
                    {2050,    1339, 614,    107,    73,    65},
                    {2250,    1600, 707,    107,    73,    65},
                    {2721,    1635, 760,    107,    76,    68},
                    {2969,    1718, 761,    106,    75,    69},
                    {3354,    1921, 813,    107,    76,    69},
                    {3799,    2150, 896,    108,    76,    68},
                    {4416,    2468, 1027,    108,    77,    69},
                    {5200,    2908, 1165,    109,    77,    69},
                    {6352,    3487, 1286,    113,    78,    70},
                    {8167,    4411, 1556,    118,    81,    70},
                    {11244,    5927, 2073,    121,    82,    73},
                    {22623,    8446, 3186, 141,    91,    87}
                    }
};

static struct pc_temp_ocv_lut feimaotui_1780_pc_temp_ocv = {
    .rows        = 29,
    .cols        = 6,
    .temp        = {-20, -10, 0, 25, 40, 60},
    .percent    = {100, 95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
    .ocv        = {
                {4171,    4166,    4163,    4161,    4156,    4152},
                {4094,    4096,    4100,    4109,    4106,    4103},
                {4042,    4050,    4057,    4066,    4063,    4060},
                {3981,    4003,    4012,    4025,    4023,    4021},
                {3939,    3959,    3974,    3987,    3987,    3985},
                {3899,    3923,    3943,    3957,    3955,    3952},
                {3869,    3886,    3912,    3928,    3926,    3923},
                {3840,    3857,    3873,    3901,    3900,    3898},
                {3821,    3830,    3842,    3869,    3873,    3871},
                {3806,    3809,    3818,    3830,    3830,    3829},
                {3791,    3797,    3799,    3810,    3810,    3809},
                {3777,    3785,    3787,    3796,    3796,    3795},
                {3763,    3773,    3779,    3784,    3785,    3783},
                {3749,    3759,    3770,    3775,    3776,    3774},
                {3736,    3743,    3760,    3767,    3765,    3761},
                {3723,    3726,    3743,    3756,    3750,    3739},
                {3709,    3711,    3718,    3735,    3729,    3719},
                {3691,    3696,    3693,    3704,    3700,    3689},
                {3657,    3677,    3677,    3684,    3679,    3669},
                {3645,    3669,    3673,    3683,    3678,    3669},
                {3632,    3661,    3668,    3682,    3677,    3667},
                {3618,    3649,    3661,    3680,    3675,    3665},
                {3601,    3634,    3653,    3674,    3670,    3661},
                {3579,    3614,    3638,    3657,    3653,    3640},
                {3549,    3585,    3608,    3620,    3616,    3601},
                {3511,    3543,    3562,    3566,    3563,    3548},
                {3457,    3484,    3492,    3493,    3490,    3475},
                {3370,    3390,    3390,    3382,    3381,    3371},
                {3200,    3200,    3200,    3200,    3200,    3200}
            }
};

static struct hisi_smartstar_coul_battery_data feimaotui_1780_battery_data = {
        .id_voltage_min = 1800,
        .id_voltage_max = 2400,
        .fcc            = 1804,
        .fcc_temp_lut        = &feimaotui_1780_fcc_temp,
        .fcc_sf_lut        = &feimaotui_1780_fcc_sf,
        .pc_temp_ocv_lut    = &feimaotui_1780_pc_temp_ocv,
        .pc_sf_lut        = &feimaotui_1780_pc_sf,
        .rbatt_sf_lut        = &feimaotui_1780_rbatt_sf,
        .default_rbatt_mohm        = 185,
        .max_currentmA = 1000,
        .max_voltagemV = 4171,
        .max_cin_currentmA = 1200,
};


